### ISSUE TITLE
XML-based terminal submission example

### ISSUE THREAD

**Issue by hoelzer** [nanozoo/wf_prepare_submission_dammit#1]
I just did manually a submission only using XML files and the terminal. 

I extracted the core information and template codes from the subsections here:
https://ena-docs.readthedocs.io/en/latest/submit/study.html

and saved it here:
https://hackmd.io/@GqOnlbqgSdKAMwgCUU_ljQ/Hklg_bDjH

I then extracted from the XML files I wrote the main parts for a metagenomic submission involving 2 samples and 3 experiments/runs (2x MiSeq, 1x Nanopore). This can be found here and might be of further use to extract a more general YML file that can then be directly parsed into the needed XML files. 

https://www.dropbox.com/s/we05es4pg8cxn8j/input.yml?dl=0

**Comment by replikation** [comment]
okay, committed. everything was working during ENA submission.
Currently, I only added the "wastewater_sludge" sample template.
I need to check out how different other templates are.
But it was super convenient for now, also checking if fastq.gz are corrupt or incomplete

e.g. feed 10 Illumina paired into it.
* creates one sample template (containing all 10 Illumina samples)
   * after submission of the template you can browse through these data sets and change/confirm
* creates one experiment template (containing all 20 Illumina file info)
   * after template submission you see everything and all the links. you can change adjust accordingly
* then you can submit everything

**Comment by replikation** [comment]
Everything was okay on my end. Total time executing and uploading the templates via web interface might be something around 5-10 mins. I was testing this with 2 illumina runs (4 files). nanopore upload of files takes a bit longer... ill do it tomorow.

> We are pleased to advise you that the metadata has passed validation and the following accession numbers have been assigned:
> 
> Please DO NOT reply to this email. If you need further assistance, contact ENA helpdesk https://www.ebi.ac.uk/ena/browser/support .
> 
> Accession Summary
> -----------------
> Type    Accession       Unique Name
> Sample  ERS3967881 (SAMEA6167881)       01-GER-illumina
> Sample  ERS3967882 (SAMEA6167882)       02-GER-illumina
> Experiment      ERX3646129      ena-EXPERIMENT-SLU-11-11-2019-17:03:38:663-1
> Experiment      ERX3646130      ena-EXPERIMENT-SLU-11-11-2019-17:03:38:664-2
> Run     ERR3654113      ena-RUN-SLU-11-11-2019-17:03:38:664-1
> Run     ERR3654114      ena-RUN-SLU-11-11-2019-17:03:38:664-2

**Comment by hoelzer** [comment]
ok, great. I think I will test this soonish with 32 Illumina groundwater_metagenomes and can add the corresponding template in this context

**Comment by hoelzer** [comment]
@replikation @phiweger Ok, this was some weird coding session. 

__Goal__:
Read in some parameters from a YAML file inside of a nextflow module. In best case, the parameters are evaluated as bash variables for direct use in other scripts or simply to write them into a file. 

__Solution__:
The repository has now a scripts folder with a shell script that holds one bash function: ``parse_yml``:

```bash
function parse_yml {
   local prefix=$2
   local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
   sed -ne "s|^\($s\):|\1|" \
        -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
   awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
         printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
      }
   }'
}
```

This function is sourced in a nextflow module and then used to evaluate a YAML file:

```bash
    #!/usr/bin/env bash

    source ${script}
    eval \$(parse_yml ${yml} "CONF_")
```

A prefix is added to not run into problems with system variables. 

Let's say the YAML file looks like this:

```yaml
global:
  debug: yes
  verbose: no
  debugging:
    detailed: no
    header: "debugging started"
```

then after the above ``eval`` one can simply access a value from the YAML file:

```bash
echo ${CONF_global_debug}
```

I just implemented one module now and added a ``--xml`` switch to the script. Will continue to add full XML support based on my recently submitted data set and then we can see how good this works. 

Nevertheless, this yml2bash script might be helpful in many other contexts later.

**Comment by replikation** [comment]
* Interesting so the goal is to add input and parse it into the xml file, and autoupload it?
* but yeah code looks "readable" :D

* btw, you can utilize the get md5 modules, as they contain "md5sum filename"

**Comment by hoelzer** [comment]
Yeah exactly. Idea is to provide some input that can not be parased from
file names (like your INPUT.txt) and generate All XML needed. Then the User
only needs to upload the read files and the XML.

Done. In an ideal World :)

Yeah saw the md5 Modules! I added some if clause to them because on my Mac
I dont have 'md5sum' and just 'md5' ;)



Christian Brandt <notifications@github.com> schrieb am Di., 12. Nov. 2019,
07:43:

**Comment by replikation** [comment]
Decided now to use both in parallel for now after talks. closing this. Both systems have advantages and disadvantages depending on the User-expertise. e.g. a bioinformatician would probably favor the xml style approach. A Biologist might favor the graphical input more. We will see how it goes :)
